version: '3.8'

services:
  app:
    build: .
    container_name: reservation_app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      APP_NAME: Reservation
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: bbase64:s3TmyEJDqZ/4G8XwhlglVSpRFVxkRMYXMiqiNAKKm+Q=
      APP_URL: http://localhost:8001

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: reservation
      DB_USERNAME: reservation
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: reservation_db
    restart: unless-stopped
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
      MYSQL_USER: reservation
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
